export const DEFAULT_DISCIPLINA_ID = '19308236';

export const DEFAULT_TEMPORADA_ID = process.env['FCF_DEFAULT_TEMPORADA_ID'] ?? '22';

export const SITEMAP_DISCIPLINA_IDS = [DEFAULT_DISCIPLINA_ID, '24694879'] as const;
